// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl72r7yfeifTECNPqdlgloihH75dODWjk',
    appId: '1:35066581744:web:0381df9216363518486835',
    messagingSenderId: '35066581744',
    projectId: 'in-1-app-76dff',
    authDomain: 'in-1-app-76dff.firebaseapp.com',
    storageBucket: 'in-1-app-76dff.firebasestorage.app',
    measurementId: 'G-KZ5RQT63RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtEQzXGn5x0OCxVwUCos1TVGPvD0jmQk',
    appId: '1:35066581744:android:6bee5700ff7a3380486835',
    messagingSenderId: '35066581744',
    projectId: 'in-1-app-76dff',
    storageBucket: 'in-1-app-76dff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHWuQKTqP5JLsf3ZwrIAY6Ug19Y1YhHY',
    appId: '1:35066581744:ios:7b807666e8c63f87486835',
    messagingSenderId: '35066581744',
    projectId: 'in-1-app-76dff',
    storageBucket: 'in-1-app-76dff.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcHWuQKTqP5JLsf3ZwrIAY6Ug19Y1YhHY',
    appId: '1:35066581744:ios:7b807666e8c63f87486835',
    messagingSenderId: '35066581744',
    projectId: 'in-1-app-76dff',
    storageBucket: 'in-1-app-76dff.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl72r7yfeifTECNPqdlgloihH75dODWjk',
    appId: '1:35066581744:web:317c5db87306f257486835',
    messagingSenderId: '35066581744',
    projectId: 'in-1-app-76dff',
    authDomain: 'in-1-app-76dff.firebaseapp.com',
    storageBucket: 'in-1-app-76dff.firebasestorage.app',
    measurementId: 'G-MRK3NX7DS4',
  );
}
